table DimDate
	lineageTag: 6a86cedc-a1fe-498e-bdf0-160ccd975a29
	dataCategory: Time

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 68a01acd-9364-4eb9-b997-7170e285539d
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 8aba0b51-9c48-43ba-ad7e-4f0cfb530bec
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ebcb6388-9749-4562-ac1c-307c5b5e4ea8
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: e04a261d-a93c-4ddf-b63c-3c3b3f884a15
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 40cd0e78-bf90-4d91-9018-290309e1e040
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: afb65c8d-96b5-4d58-884c-7c145a108959
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNumber

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: e0743335-54e2-4dac-9816-af126103d594
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 59d23a26-fa95-4acc-9773-d50ecdbc98dc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = User

	column DayName
		dataType: string
		lineageTag: 8fe35b91-62e4-4d58-a5e3-f659e04c7742
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: 855c96e9-aa97-4bb9-8cd5-4b733dc7ac21
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	hierarchy Calendar
		lineageTag: 4b14ba0e-d035-4cd9-bcf7-efdf401759ae

		level Year
			lineageTag: 9ea384a6-4793-47da-976b-6e6ebed4f0b3
			column: Year

		level Quarter
			lineageTag: b41c2c9f-70b3-4a48-abc2-7236ae61ca3d
			column: Quarter

		level Month
			lineageTag: 1b7bc302-1833-47ed-94c5-e1b2eacb0163
			column: MonthName

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://raw.githubusercontent.com/nguyenthientinpotato/data-analytics-portfolio/main/projects/pharmacy-sales-and-profitability/data/Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    T_DimDate_Table = Source{[Item="T_DimDate",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_DimDate_Table,{{"Date", type date}, {"DateKey", Int64.Type}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"YearMonth", type text}}),
				    #"Added DayOfWeek" = Table.AddColumn(#"Changed Type", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday), Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"), type text),
				    #"Added DayType" = Table.AddColumn(#"Added DayName", "DayType", each if [DayOfWeek] >= 5 then "Weekend" else "Weekday", type text)
				in
				    #"Added DayType"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

